# dashboard_faturamento.py
import pandas as pd
from dash import Dash, dcc, html, Input, Output
import plotly.express as px

# === Carregar os dados ===
df = pd.read_excel("Python.xlsx")

# Padronizar nomes de colunas
df.columns = df.columns.str.strip().str.replace(".", " ", regex=False).str.title()
df.rename(columns={"Faturamento Do Serviço": "Faturamento"}, inplace=True)

# Garantir que a coluna "Faturamento" seja numérica
df["Faturamento"] = pd.to_numeric(df["Faturamento"], errors="coerce").fillna(0)

# === App Dash ===
app = Dash(__name__)
app.title = "Faturamento por Colaborador"

# === Layout ===
app.layout = html.Div([
    html.H1("📊 Dashboard de Faturamento por Colaborador", style={"textAlign": "center"}),

        html.Div([
                html.Div([
                            html.Label("Grupo:"),
                                        dcc.Dropdown(
                                                        options=[{"label": g, "value": g} for g in sorted(df["Grupo"].dropna().unique())],
                                                                        id="grupo-filter",
                                                                                        placeholder="Selecione um grupo",
                                                                                                        clearable=True
                                                                                                                    )
                                                                                                                            ], style={"width": "24%", "display": "inline-block", "padding": "5px"}),

                                                                                                                                    html.Div([
                                                                                                                                                html.Label("Classificação:"),
                                                                                                                                                            dcc.Dropdown(
                                                                                                                                                                            options=[{"label": c, "value": c} for c in sorted(df["Classificação"].dropna().unique())],
                                                                                                                                                                                            id="class-filter",
                                                                                                                                                                                                            placeholder="Selecione uma classificação",
                                                                                                                                                                                                                            clearable=True
                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                ], style={"width": "24%", "display": "inline-block", "padding": "5px"}),

                                                                                                                                                                                                                                                        html.Div([
                                                                                                                                                                                                                                                                    html.Label("Regime:"),
                                                                                                                                                                                                                                                                                dcc.Dropdown(
                                                                                                                                                                                                                                                                                                options=[{"label": r, "value": r} for r in sorted(df["Regime"].dropna().unique())],
                                                                                                                                                                                                                                                                                                                id="regime-filter",
                                                                                                                                                                                                                                                                                                                                placeholder="Selecione um regime",
                                                                                                                                                                                                                                                                                                                                                clearable=True
                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                    ], style={"width": "24%", "display": "inline-block", "padding": "5px"}),
                                                                                                                                                                                                                                                                                                                                                                        ]),

                                                                                                                                                                                                                                                                                                                                                                            html.Br(),

                                                                                                                                                                                                                                                                                                                                                                                html.Div(id="kpi-container", style={"textAlign": "center"}),

                                                                                                                                                                                                                                                                                                                                                                                    html.Br(),

                                                                                                                                                                                                                                                                                                                                                                                        html.Div([
                                                                                                                                                                                                                                                                                                                                                                                                dcc.Graph(id="ranking-colaboradores", style={"width": "48%", "display": "inline-block"}),
                                                                                                                                                                                                                                                                                                                                                                                                        dcc.Graph(id="faturamento-grupo", style={"width": "48%", "display": "inline-block"})
                                                                                                                                                                                                                                                                                                                                                                                                            ]),

                                                                                                                                                                                                                                                                                                                                                                                                                html.Div([
                                                                                                                                                                                                                                                                                                                                                                                                                        dcc.Graph(id="faturamento-classificacao", style={"width": "98%", "display": "inline-block"})
                                                                                                                                                                                                                                                                                                                                                                                                                            ])
                                                                                                                                                                                                                                                                                                                                                                                                                            ])

                                                                                                                                                                                                                                                                                                                                                                                                                            # === Callbacks ===
                                                                                                                                                                                                                                                                                                                                                                                                                            @app.callback(
                                                                                                                                                                                                                                                                                                                                                                                                                                [Output("ranking-colaboradores", "figure"),
                                                                                                                                                                                                                                                                                                                                                                                                                                     Output("faturamento-grupo", "figure"),
                                                                                                                                                                                                                                                                                                                                                                                                                                          Output("faturamento-classificacao", "figure"),
                                                                                                                                                                                                                                                                                                                                                                                                                                               Output("kpi-container", "children")],
                                                                                                                                                                                                                                                                                                                                                                                                                                                   [Input("grupo-filter", "value"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Input("class-filter", "value"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                             Input("regime-filter", "value")]
                                                                                                                                                                                                                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                                                                                                                                                                                                                             def update_dashboard(grupo, classificacao, regime):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 dff = df.copy()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                     # Aplicar filtros
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if grupo:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 dff = dff[dff["Grupo"] == grupo]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if classificacao:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             dff = dff[dff["Classificação"] == classificacao]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if regime:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         dff = dff[dff["Regime"] == regime]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             # === KPI principal ===
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 total_faturamento = dff["Faturamento"].sum()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     total_colaboradores = dff["Colaborador"].nunique()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         kpi = html.Div([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 html.H3(f"💰 Faturamento Total: R$ {total_faturamento:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         html.H4(f"👥 Colaboradores Ativos: {total_colaboradores}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 # === Ranking de colaboradores ===
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ranking = dff.groupby("Colaborador")["Faturamento"].sum().reset_index().sort_values(by="Faturamento", ascending=False)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         fig_ranking = px.bar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ranking,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         x="Colaborador",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 y="Faturamento",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         title="Ranking de Faturamento por Colaborador",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 color_discrete_sequence=["#003366"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         # === Faturamento por grupo ===
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             faturamento_grupo = dff.groupby("Grupo")["Faturamento"].sum().reset_index()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fig_grupo = px.bar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         faturamento_grupo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 x="Grupo",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         y="Faturamento",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 title="Faturamento por Grupo",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         color_discrete_sequence=["#006699"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 # === Faturamento por classificação ===
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     faturamento_classificacao = dff.groupby("Classificação")["Faturamento"].sum().reset_index()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         fig_classificacao = px.bar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 faturamento_classificacao,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         x="Classificação",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 y="Faturamento",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         title="Faturamento por Classificação",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 color_discrete_sequence=["#0099CC"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return fig_ranking, fig_grupo, fig_classificacao, kpi

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         # === Rodar o servidor ===
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             app.run(debug=True, port=8502, host="0.0.0.0")

